# Generated by Django 5.2.5 on 2026-08-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('accounts', '0002_profile_edit'),
    ]

    operations = [
    ]
