# Generated by Django 5.2.5 on 2026-08-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='call',
            new_name='calls_call_receive_b2ddac_idx',
            old_name='calls_call_receiv_1b8f1d_idx',
        ),
        migrations.RenameIndex(
            model_name='call',
            new_name='calls_call_convers_0e19f0_idx',
            old_name='calls_call_conve_6f7d3b_idx',
        ),
    ]
