# Generated by Django 5.2.5 on 2026-08-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_history'),
        ('calls', '0002_rename_calls_call_receiv_1b8f1d_idx_calls_call_receive_b2ddac_idx_and_more'),
    ]

    operations = [
    ]
