# Generated by Django 5.2.5 on 2026-08-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_listinglike'),
        ('catalog', '0004_listing_offer_fields'),
    ]

    operations = [
    ]
