# Generated by Django 5.2.5 on 2026-08-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_merge_0002_listinglike_0004_listing_offer_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listinglike',
            new_name='catalog_lis_listing_9e9a38_idx',
            old_name='catalog_listinglike_listing_created_idx',
        ),
    ]
