# Generated by Django 5.2.5 on 2026-08-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_listingimage_cloudinary_public_id'),
        ('catalog', '0006_rename_catalog_listinglike_listing_created_idx_catalog_lis_listing_9e9a38_idx'),
    ]

    operations = [
    ]
