# Generated by Django 5.2.5 on 2026-08-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_merge_20260814_2034'),
        ('catalog', '0008_listingimage_seed_image_blob'),
    ]

    operations = [
    ]
