# Generated by Django 5.2.5 on 2026-08-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_marketplaceevent'),
        ('catalog', '0009_merge_20260814_2057'),
    ]

    operations = [
    ]
