# Generated by Django 5.2.5 on 2026-08-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_cartitem'),
        ('catalog', '0010_merge_0009_marketplaceevent_0009_merge_20260814_2057'),
    ]

    operations = [
    ]
