# Generated by Django 5.2.5 on 2026-08-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_merge_20260815_2302'),
        ('catalog', '0011_storeemailverification'),
    ]

    operations = [
    ]
