# Generated by Django 5.2.5 on 2026-08-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_merge_20260816_0210'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='catalog_car_user_id_04d340_idx',
            old_name='catalog_car_user_id_8c3d2b_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='catalog_car_listing_ae6d0e_idx',
            old_name='catalog_car_listing_9b4f31_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplaceevent',
            new_name='catalog_mar_user_id_d633ec_idx',
            old_name='catalog_mar_user_id_6a0a42_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplaceevent',
            new_name='catalog_mar_user_id_17f2ca_idx',
            old_name='catalog_mar_user_id_0f1a3a_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplaceevent',
            new_name='catalog_mar_user_id_2433c2_idx',
            old_name='catalog_mar_user_id_3e9d5f_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplaceevent',
            new_name='catalog_mar_user_id_ee13ce_idx',
            old_name='catalog_mar_user_id_7c7f8d_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplaceevent',
            new_name='catalog_mar_event_f30261_idx',
            old_name='catalog_mar_event_i_9f7f34_idx',
        ),
    ]
