# Generated by Django 5.2.5 on 2026-08-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_product_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='buyer_typing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='seller_typing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
